### ISSUE TITLE
Falied to load the gitter package

### ISSUE THREAD

**Issue by JLLeitschuh** [Glavin001/atom-gitter#37]
1. Install app in atom

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.3
**Thrown From**: [gitter](git://github.com/Glavin001/atom-gitter) package, v0.6.2
### Stack Trace

Failed to load the gitter package

```
At ENOENT: no such file or directory, open '/Users/jonathan.leitschuh/.atom/packages/gitter/node_modules/emojify.js/dist/js/emojify.js'

Error: ENOENT: no such file or directory, open '/Users/jonathan.leitschuh/.atom/packages/gitter/node_modules/emojify.js/dist/js/emojify.js'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.readFileSync (fs.js:396:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
    at module.exports (/Users/jonathan.leitschuh/.atom/packages/gitter/lib/execFile.coffee:10:15)
    at /Users/jonathan.leitschuh/.atom/packages/gitter/lib/emojify.coffee:10:12
    at Object.<anonymous> (/Users/jonathan.leitschuh/.atom/packages/gitter/lib/emojify.coffee:11:5)
    at Object.<anonymous> (/Users/jonathan.leitschuh/.atom/packages/gitter/lib/emojify.coffee:13:4)
    at Module._compile (module.js:452:26)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.0
editor-stats, v0.17.0
emmet, v2.3.10
gitter, v0.6.2
linter, v0.12.7
linter-jshint, v0.1.6
minimap, v4.10.0
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
I am no longer personally maintaining Atom Gitter. However, I will review and accept pull requests.
